POST http://localhost:3000/mongoaddScore HTTP/1.1
content-type: application/json

{
    "name": "BABA record",
    "points": 1221,
    "comment": ""
}

###

GET http://localhost:3000/getFullLeaderboard HTTP/1.1


###  userStat
POST http://localhost:3000/mongoaddUserStat HTTP/1.1
content-type: application/json

{
     "userName": "userAdam",
     "wins": 2,
     "loses": 5
}
###

POST http://localhost:3000/mongoaddScore HTTP/1.1
content-type: application/json

{
    "name": "piece77",
    "position": {
      "index": 1,
      "level": 1
    },
    "color": 1
}

###

POST http://localhost:3000/endGame HTTP/1.1
content-type: application/json

{
      "winner": "Kasia",
      "loser": "Asia"
}

###

GET http://localhost:3000/getGamesHistory HTTP/1.1
###

GET http://localhost:3000/getAllStat HTTP/1.1


###
GET http://localhost:3000/getSpecificUserStat/?user=Adam HTTP/1.1

###

POST http://localhost:3000/mongoaddUserStat HTTP/1.1
content-type: application/json

{
      "userColor": 1,
      "result": "win"
}

###