POST http://localhost:3000/mongoaddScore HTTP/1.1
content-type: application/json

{
    "name": "BABA record",
    "points": 1221,
    "comment": ""
}

###

GET http://localhost:3000/getFullLeaderboard HTTP/1.1

###


POST http://localhost:3000/mongoaddScore HTTP/1.1
content-type: application/json

{
    "name": "piece77",
    "position": {
      "index": 1,
      "level": 1
    },
    "color": 1
}
