export default [
  { name: 'piece1', position: { index: 6, level: 1 }, color: 2 },
  { name: 'piece2', position: { index: 6, level: 2 }, color: 2 },
  { name: 'piece3', position: { index: 6, level: 3 }, color: 2 },
  { name: 'piece4', position: { index: 6, level: 4 }, color: 2 },
  { name: 'piece5', position: { index: 6, level: 5 }, color: 2 },
  { name: 'piece6', position: { index: 8, level: 1 }, color: 2 },
  { name: 'piece7', position: { index: 8, level: 2 }, color: 2 },
  { name: 'piece8', position: { index: 8, level: 3 }, color: 2 },
  { name: 'piece9', position: { index: 13, level: 1 }, color: 2 },
  { name: 'piece10', position: { index: 13, level: 2 }, color: 2 },
  { name: 'piece11', position: { index: 13, level: 3 }, color: 2 },
  { name: 'piece12', position: { index: 13, level: 4 }, color: 2 },
  { name: 'piece13', position: { index: 13, level: 5 }, color: 2 },
  { name: 'piece14', position: { index: 24, level: 1 }, color: 2 },
  { name: 'piece15', position: { index: 24, level: 2 }, color: 2 },

  { name: 'piece16', position: { index: 1, level: 1 }, color: 1 },
  { name: 'piece17', position: { index: 1, level: 2 }, color: 1 },
  { name: 'piece18', position: { index: 12, level: 1 }, color: 1 },
  { name: 'piece19', position: { index: 12, level: 2 }, color: 1 },
  { name: 'piece20', position: { index: 12, level: 3 }, color: 1 },
  { name: 'piece21', position: { index: 12, level: 4 }, color: 1 },
  { name: 'piece22', position: { index: 12, level: 5 }, color: 1 },
  { name: 'piece23', position: { index: 17, level: 1 }, color: 1 },
  { name: 'piece24', position: { index: 17, level: 2 }, color: 1 },
  { name: 'piece25', position: { index: 17, level: 3 }, color: 1 },
  { name: 'piece26', position: { index: 19, level: 1 }, color: 1 },
  { name: 'piece27', position: { index: 19, level: 2 }, color: 1 },
  { name: 'piece28', position: { index: 19, level: 3 }, color: 1 },
  { name: 'piece29', position: { index: 19, level: 4 }, color: 1 },
  { name: 'piece30', position: { index: 19, level: 5 }, color: 1 },
];
